# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
