#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Feb 09 19:13:56 EST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 554316da6dc14a1a9a91c2ade7e1ca4a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot wallace_8x8_product_tb_behav xil_defaultlib.wallace_8x8_product_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 554316da6dc14a1a9a91c2ade7e1ca4a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot wallace_8x8_product_tb_behav xil_defaultlib.wallace_8x8_product_tb xil_defaultlib.glbl -log elaborate.log

