webtalk_init -webtalk_dir /home/mr-robot/Documents/arch/module04/fp_algorithms/fp_algorithms.sim/sim_1/behav/xsim/xsim.dir/fadder_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 19 20:13:51 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "565ce6ea-84e5-4098-86e7-23b448243233" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2428e96babb5418e96e7d04eb510920f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Parrot" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Parrot GNU/Linux 4.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2111.999 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116068_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1305893886 -regid "" -xml /home/mr-robot/Documents/arch/module04/fp_algorithms/fp_algorithms.sim/sim_1/behav/xsim/xsim.dir/fadder_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/mr-robot/Documents/arch/module04/fp_algorithms/fp_algorithms.sim/sim_1/behav/xsim/xsim.dir/fadder_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/mr-robot/Documents/arch/module04/fp_algorithms/fp_algorithms.sim/sim_1/behav/xsim/xsim.dir/fadder_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
