# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.runs/synth_1/mfp_nexys4_ddr.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.cache/wt} [current_project]
set_property parent.project_path {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {/home/besernd1/otherrepo/basic/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/3rd Party IP/uart-debug/ascii.vh}
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/mfp_ahb_const.vh
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/inst_present.vh}
}
set_property file_type "Verilog Header" [get_files {{/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/3rd Party IP/uart-debug/ascii.vh}}]
set_property file_type "Verilog Header" [get_files {{/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/inst_present.vh}}]
read_verilog -library xil_defaultlib {
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/io/SPI_Master.v
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/3rd Party IP/uart-debug/UART_RX.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/3rd Party IP/uart-debug/UART_TX.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/add.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/addsub32.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/alu_ov.v}
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/io/buzzer.v
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/cla32.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/cla_16.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/cla_2.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/cla_32.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/cla_4.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/cla_8.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/3rd Party IP/uart-debug/cmdproc.v}
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/io/cpugpio.v
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/3rd Party IP/examples/debug_control.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/dff32.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/dffe32.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/gp.v}
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/io/milliscounter.v
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/mips_bad_inst_det.v
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/mux2x32.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/mux2x5.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/mux4x32.v}
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/io/pmod_als_spi_receiver.v
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/regfile.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/sc_interrupt.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/sccomp_decoder.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/sccpu_intr.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/sccu_intr.v}
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/sevensegdec.v}
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/io/sevensegtimer.v
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/shift.v}
  /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/uram.v
  {/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/imports/sccompintFPGA/mfp_nexys4_ddr.v}
}
read_ip -quiet {{/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc}}]
set_property used_in_implementation false [get_files -all {{/home/mr-robot/Documents/arch/module01/mips-cpu/RTL/CPUs/Single Cycle with Interrupts/sccompintFPGA.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/mfp_nexys4_ddr.xdc
set_property used_in_implementation false [get_files /home/mr-robot/Documents/arch/module01/mips-cpu/RTL/Common/mfp_nexys4_ddr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mfp_nexys4_ddr -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mfp_nexys4_ddr.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mfp_nexys4_ddr_utilization_synth.rpt -pb mfp_nexys4_ddr_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
