// TOOL:     vlog2tf
// DATE:     Fri Apr 12 15:54:29 2013
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   Booth_mult
// DESIGN:   Booth_mult
// FILENAME: Booth_mult_tf.v
// PROJECT:  Unknown
// VERSION:  2.0
// This file is auto generated by the Diamond

`timescale 1 ns / 100 ps

// Define Module for Test Fixture
module Booth_mult_tb();
    // Inputs
    reg [15:0] mplier;
    reg [15:0] mcand;
    reg n_reset;
    reg start;
    reg clk;

    // Outputs
    wire [31:0] product;
    wire done;

    // Instantiate the UUT
    // Please check and add your parameters manually
    Booth_mult
    #(.N(16))
    UUT (
    .product(product), 
    .done(done), 
    .mplier(mplier), 
    .mcand(mcand), 
    .n_reset(n_reset), 
    .start(start), 
    .clk(clk)
    );


    // Initialize Inputs
    // You can add your stimulus here
    initial begin
            mplier = 0;
            mcand = 0;
            n_reset = 0;
            start = 0;
            clk = 0;
    end

	always #20 clk = ~clk;
	
	//display variables
    initial $monitor ("mcand = %d, mplier = %d, product = %d, start = %d, done = %d", mcand, mplier, product, start, done);
	
	initial begin
	        //// 16-bit test
			//// mcand = 112
			//// mplier = 14
			//// prod = 1568
			#4000
				n_reset = 1'b1;
			#4000
				mcand = 16'b0000000001110000;
				mplier = 16'b0000000000001110;
			#40
				start = 1'b1;
			#40
				start = 1'b0;		
			
			//// 16-bit test
			//// mcand = 64792
			//// mplier = 16198
			//// prod = 1049500816
			#400
				mcand = 16'b1111110100011000;
				mplier = 16'b0011111101000110;
			#40
				start = 1'b1;
			#40
				start = 1'b0;
			
			//// 16-bit test
			//// mcand = 65535
			//// mplier = 65535
			//// quot = 4294836225	
			#400
				mcand = 16'b1111111111111111;
				mplier = 16'b1111111111111111;
			#40
				start = 1'b1;
			#40
				start = 1'b0;
				
			//// 16-bit test
			//// mcand = 15
			//// mplier = 9
			//// quot = 135
			#400
				mcand = 16'b0000000000001111;
				mplier = 16'b0000000000001001;
			#40
				start = 1'b1;
			#40
				start = 1'b0;	
			
			//// reset back to zero
			#400
				mcand = 0;
				mplier = 0;
				
			$finish;
    end
endmodule